### ISSUE TITLE
App crash if call show when minimized

### ISSUE THREAD

**Issue by robertolocal** [NiklasMerz/cordova-plugin-fingerprint-aio#100]
## Description
App crash if call show when minimized.

* Plugin version: latest
* Android version: 6, 7 and 8

**Comment by robertolocal** [comment]
Crash if pause app after call show too. With the fingerprint dialog opened.

**Comment by NiklasMerz** [comment]
Can you provide the output of logcat or a stacktrace?

**Comment by robertolocal** [comment]
06-29 15:33:23.957 13214-14599/com.localdrive.app V/Fingerprint: Fingerprint action: authenticate
06-29 15:33:24.020 13214-14599/com.localdrive.app W/PluginManager: THREAD WARNING: exec() call to Fingerprint.authenticate blocked the main thread for 64ms. Plugin should use CordovaInterface.getThreadPool().
06-29 15:33:24.087 13214-13214/com.localdrive.app D/AndroidRuntime: Shutting down VM
06-29 15:33:24.091 13214-13214/com.localdrive.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.localdrive.app, PID: 13214
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1870)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1893)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
        at android.app.BackStackRecord.commit(BackStackRecord.java:646)
        at android.app.DialogFragment.show(DialogFragment.java:233)
        at de.niklasmerz.cordova.fingerprint.Fingerprint$1.run(Fingerprint.java:215)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
06-29 15:33:24.099 13214-13214/com.localdrive.app E/com.marianhello.logging.UncaughtExceptionLogger: FATAL EXCEPTION: mainjava.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1870)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1893)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:688)
        at android.app.BackStackRecord.commit(BackStackRecord.java:646)
        at android.app.DialogFragment.show(DialogFragment.java:233)
        at de.niklasmerz.cordova.fingerprint.Fingerprint$1.run(Fingerprint.java:215)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by robertolocal** [comment]
Seems to be something related to: https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth/issues/54

**Comment by NiklasMerz** [comment]
Please see #81 for a possible fix

**Comment by akshaytaywade** [comment]
still i am facing issue the app is crashing when the home button and fingerprint is touched at the same time and the app wents to background please help


 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1438)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1456)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
        at android.app.BackStackRecord.commit(BackStackRecord.java:671)
        at android.app.DialogFragment.dismissInternal(DialogFragment.java:304)
        at android.app.DialogFragment.dismiss(DialogFragment.java:270)
        at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated(FingerprintAuthenticationDialogFragment.java:245)
        at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run(FingerprintUiHelper.java:148)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
