### ISSUE TITLE
Finger print and home button touch simultaneously app is getting crashed on samsung s6 , and in all other devices 

### ISSUE THREAD

**Issue by akshaytaywade** [NiklasMerz/cordova-plugin-fingerprint-aio#141]
Still i am facing issue when the home button and finger print are pressed together the app went into back ground and app crashes

Fingerprint aio plugin version :1.5.0

Ionic version :3.9.2
Cordova version : 8

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1438)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1456)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
at android.app.BackStackRecord.commit(BackStackRecord.java:671)
at android.app.DialogFragment.dismissInternal(DialogFragment.java:304)
at android.app.DialogFragment.dismiss(DialogFragment.java:270)
at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated(FingerprintAuthenticationDialogFragment.java:245)
at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run(FingerprintUiHelper.java:148)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by akshaytaywade** [comment]
Hi NiklasMerz

i am facing issue still app is getting crashed when fingerprint and home button are touched simultaneously

installed : cordova plugin add cordova-plugin-fingerprint-aio@rc

Cordova version : 8.1.2
Ionic version : 3.9.2

Error log cat:

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1438)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1456)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
at android.app.BackStackRecord.commit(BackStackRecord.java:671)
at android.app.DialogFragment.dismissInternal(DialogFragment.java:304)
at android.app.DialogFragment.dismiss(DialogFragment.java:270)
at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated(FingerprintAuthenticationDialogFragment.java:245)
at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run(FingerprintUiHelper.java:148)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

My ### package.json

{
"name": "XYZ",
"version": "0.0.1",
"author": "Ionic Framework",
"homepage": "http://ionicframework.com/",
"private": true,
"scripts": {
"start": "ionic-app-scripts serve",
"clean": "ionic-app-scripts clean",
"build": "ionic-app-scripts build",
"lint": "ionic-app-scripts lint"
},
"dependencies": {
"@angular/animations": "5.2.11",
"@angular/common": "5.2.11",
"@angular/compiler": "5.2.11",
"@angular/compiler-cli": "5.2.11",
"@angular/core": "5.2.11",
"@angular/forms": "5.2.11",
"@angular/http": "5.2.11",
"@angular/platform-browser": "5.2.11",
"@angular/platform-browser-dynamic": "5.2.11",
"@ionic-native/app-update": "^4.15.0",
"@ionic-native/app-version": "^4.19.0",
"@ionic-native/core": "~4.12.0",
"@ionic-native/diagnostic": "^4.15.0",
"@ionic-native/dialogs": "^4.19.0",
"@ionic-native/fcm": "^4.19.0",
"@ionic-native/fingerprint-aio": "^4.19.0",
"@ionic-native/in-app-browser": "^4.19.0",
"@ionic-native/network": "^4.19.0",
"@ionic-native/open-native-settings": "^4.19.0",
"@ionic-native/splash-screen": "~4.12.0",
"@ionic-native/status-bar": "~4.12.0",
"@ionic-native/toast": "^4.19.0",
"@ionic/storage": "2.2.0",
"@ngx-translate/core": "^9.1.1",
"@ngx-translate/http-loader": "^2.0.1",
"com.cordova.plugins.cookiemaster": "^1.0.1",
"cordova-android": "6.2.0",
"cordova-open-native-settings": "1.5.2",
"cordova-plugin-app-update": "file:../Downloads/projectdocuments/cordova-plugin-app-update",
"cordova-plugin-app-version": "0.1.9",
"cordova-plugin-appversion": "^1.0.0",
"cordova-plugin-compat": "^1.2.0",
"cordova-plugin-cookiemaster": "^1.0.5",
"cordova-plugin-device": "^2.0.2",
"cordova-plugin-dialogs": "2.0.1",
"cordova-plugin-fcm-with-dependecy-updated": "2.4.0",
"cordova-plugin-fingerprint-aio": "1.5.0",
"cordova-plugin-inappbrowser": "3.0.0",
"cordova-plugin-ionic-keyboard": "^2.1.3",
"cordova-plugin-ionic-webview": "^2.3.2",
"cordova-plugin-network-information": "2.0.1",
"cordova-plugin-secure-key-store": "^1.5.5",
"cordova-plugin-splashscreen": "^5.0.2",
"cordova-plugin-statusbar": "^2.4.2",
"cordova-plugin-whitelist": "^1.3.3",
"cordova-plugin-x-toast": "2.7.2",
"cordova.plugins.diagnostic": "^3.9.2",
"ionic-angular": "3.9.2",
"ionicons": "3.0.0",
"rxjs": "5.5.11",
"sw-toolbox": "3.6.0",
"zone.js": "0.8.26"
},
"devDependencies": {
"@ionic/app-scripts": "3.2.0",
"typescript": "~2.6.2"
},
"description": "An Ionic project",
"cordova": {
"plugins": {
"cordova-plugin-whitelist": {},
"cordova-plugin-statusbar": {},
"cordova-plugin-device": {},
"cordova-plugin-splashscreen": {},
"cordova-plugin-ionic-webview": {},
"cordova-plugin-ionic-keyboard": {},
"com.cordova.plugins.cookiemaster": {},
"cordova-open-native-settings": {},
"cordova-plugin-dialogs": {},
"cordova-plugin-fingerprint-aio": {},
"cordova-plugin-inappbrowser": {},
"cordova-plugin-network-information": {},
"cordova-plugin-secure-key-store": {},
"cordova-plugin-x-toast": {},
"cordova.plugins.diagnostic": {},
"cordova-plugin-fcm-with-dependecy-updated": {},
"cordova-plugin-app-version": {},
"cordova-plugin-app-update": {},
"cordova-plugin-compat": {}
},
"platforms": [
"android"
]
}
}

**Comment by NiklasMerz** [comment]
Thanks @akshaytaywade . Since #132 already discusses this I am closing this issue.
