### ISSUE TITLE
App Crash on Samsung S7, Android 6.0.1

### ISSUE THREAD

**Issue by helmbrecht** [NiklasMerz/cordova-plugin-fingerprint-aio#15]
Steps:
1. I click on "Cancel"
2. After that I click on Android Home Button (pause)

Then there is an app crash:

>
03-28 21:16:09.622: E/AndroidRuntime(26323): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1428)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1446)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.DialogFragment.show(DialogFragment.java:230)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at **de.niklasmerz.cordova.fingerprint.Fingerprint$1.run(Fingerprint.java:215)**
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.os.Handler.handleCallback(Handler.java:739)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.os.Looper.loop(Looper.java:158)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at android.app.ActivityThread.main(ActivityThread.java:7229)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at java.lang.reflect.Method.invoke(Native Method)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-28 21:16:09.622: E/AndroidRuntime(26323): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
03-28 21:16:09.642: E/android.os.Debug(4998): ro.product_ship = true

**Comment by helmbrecht** [comment]
Sorry, was my mistake, on pause I set the root page and this page loaded a page that contained the fingerprint, this caused the issue
