### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by MattiaMalonni** [NiklasMerz/cordova-plugin-fingerprint-aio#233]
# Bug report

## Description
* What did happen? App crash
* What did you expect to happen? Ask for fingerprint

## Environment

* Plugin version: 3.0.1
* Build environment: Android 9 - cordova 8.1.2 (cordova-lib@8.1.1)  - cordova-android: 8.1.0
* Build platform: android

### Logs
  <pre>android.content.ActivityNotFoundException: Unable to find explicit activity class {application/de.niklasmerz.cordova.biometric.BiometricActivity}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2020)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1677)
    at android.app.Activity.startActivityForResult(Activity.java:4689)
    at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:345)
    at android.app.Activity.startActivityForResult(Activity.java:4647)
    at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:68)
    at de.niklasmerz.cordova.biometric.Fingerprint.lambda$executeAuthenticate$0(Fingerprint.java:72)
    at de.niklasmerz.cordova.biometric.-$$Lambda$Fingerprint$W8uV5vVOnMVXV1BBIzzXTZry-UQ.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7099)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)</pre>

**Comment by d-weston** [comment]
What was the solution here?

**Comment by FlorinSerban** [comment]
Hi,
I have the same behavior.
Can you please post the solution?

**Comment by HellMaX** [comment]
Hi,

Does someone found the solution ?

Thanks

**Comment by FlorinSerban** [comment]
Hi,

My problem was not related to this plugin.
I was receiving that error because I had a bug in my config.xml file.
For example I was using wrong the **edit-config** tag and because of this, AndroidManifest.xml file was rewritten with the wrong information. 

I hope this will help you.

**Comment by leitonet** [comment]
Hi @FlorinSerban. I can't see any error in my AndroidManifest.xml. 
What is the right section of AndroidManifest.xml that should be created by this plugin? I can't see any BiometricActivity declared in the manifest.
Thanks

**Comment by leitonet** [comment]
I'm using ionic + cordova. Finally I solved it adding this in the config.xml:

```
<config-file parent="application" target="AndroidManifest.xml">
            <activity android:exported="true" android:name="de.niklasmerz.cordova.biometric.BiometricActivity" android:theme="@style/TransparentTheme" />
</config-file>
```

**Comment by FlorinSerban** [comment]
Hi @leitonet,
That line should be automatically added by the plugin.
If it's not added, something my be wrong with your config.xml

**Comment by leolio86400** [comment]
seems that the plugin.xml file is the responsible for this issue, most likely related to cordova upgrade

```
<config-file target="AndroidManifest.xml" parent="/manifest/application">
```

to:
```
<config-file target="app/src/main/AndroidManifest.xml" parent="/manifest/application">
```
