### ISSUE TITLE
NullPointerException in crash logs

### ISSUE THREAD

**Issue by adamdport** [NiklasMerz/cordova-plugin-fingerprint-aio#370]
## Description

I haven't had any issues locally but I noticed a nullpointerexecption in my app's crash logs: 

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4869)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4906)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8528)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5511)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4856)
Caused by: java.lang.NullPointerException: 
  at de.niklasmerz.cordova.biometric.Fingerprint.lambda$sendError$1$Fingerprint (Fingerprint.java:161)
  at de.niklasmerz.cordova.biometric.-$$Lambda$Fingerprint$HQesV6eLUymiZZSDRXppmLSXqEY.run (Unknown Source:4)
  at android.app.Activity.runOnUiThread (Activity.java:7154)
  at de.niklasmerz.cordova.biometric.Fingerprint.sendError (Fingerprint.java:160)
  at de.niklasmerz.cordova.biometric.Fingerprint.sendError (Fingerprint.java:132)
  at de.niklasmerz.cordova.biometric.Fingerprint.onActivityResult (Fingerprint.java:115)
  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult (CordovaInterfaceImpl.java:159)
  at org.apache.cordova.CordovaActivity.onActivityResult (CordovaActivity.java:368)
  at android.app.Activity.dispatchActivityResult (Activity.java:8550)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5504)
```
## Environment

"cordova-plugin-fingerprint-aio": "4.0.2",
"cordova-android": "9.1.0",

Android 11 (SDK 30)
Samsung Galaxy A32 5G
Samsung Galaxy A12

### Logs

<details>
  <pre>```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4869)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:4906)
  at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:52)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8528)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5511)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4856)
Caused by: java.lang.NullPointerException: 
  at de.niklasmerz.cordova.biometric.Fingerprint.lambda$sendError$1$Fingerprint (Fingerprint.java:161)
  at de.niklasmerz.cordova.biometric.-$$Lambda$Fingerprint$HQesV6eLUymiZZSDRXppmLSXqEY.run (Unknown Source:4)
  at android.app.Activity.runOnUiThread (Activity.java:7154)
  at de.niklasmerz.cordova.biometric.Fingerprint.sendError (Fingerprint.java:160)
  at de.niklasmerz.cordova.biometric.Fingerprint.sendError (Fingerprint.java:132)
  at de.niklasmerz.cordova.biometric.Fingerprint.onActivityResult (Fingerprint.java:115)
  at org.apache.cordova.CordovaInterfaceImpl.onActivityResult (CordovaInterfaceImpl.java:159)
  at org.apache.cordova.CordovaActivity.onActivityResult (CordovaActivity.java:368)
  at android.app.Activity.dispatchActivityResult (Activity.java:8550)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5504)
```</pre>
</details>

**Comment by OtherCarlos** [comment]
Same here. Used to failed with Samsung devices and some Xiaomi another common case is Android 11. I have the same Issue on Production with some users where the App crash when use Fingerprint:

## Environment

"cordova-plugin-fingerprint-aio": "4.0.2",
"cordova-android": "9.1.0",

Android 11 (SDK 30)
- Redmi Note 9
- Redmi Note 8
- POCO X3 Pro
- Galaxy J7 Prime
- Galaxy A30

### Logs

<details>
  <pre>
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.sendPluginResult(org.apache.cordova.PluginResult)' on a null object reference
       at de.niklasmerz.cordova.biometric.Fingerprint.lambda$sendError$1$Fingerprint(Fingerprint.java:117)
       at de.niklasmerz.cordova.biometric.-$$Lambda$Fingerprint$HQesV6eLUymiZZSDRXppmLSXqEY.run(:4)
       at android.app.Activity.runOnUiThread(Activity.java:7153)
       at de.niklasmerz.cordova.biometric.Fingerprint.sendError(Fingerprint.java:116)
       at de.niklasmerz.cordova.biometric.Fingerprint.onActivityResult(Fingerprint.java:89)
       at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
       at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:368)
       at android.app.Activity.dispatchActivityResult(Activity.java:8476)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5132)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4532)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4577)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
</pre>
</details>

**Comment by rahulsingh8990** [comment]
I am also facing the same issue, do we have update on this.? @NiklasMerz

**Comment by minduch** [comment]
I wound't know why the `callbackContext` is null, but it would certainly avoid the `NullPointerExceptions`and be thread-safe.

**Comment by bhargavas12** [comment]
any update on this ?

**Comment by haziqali-2019** [comment]
same issue on samsung devices
