### ISSUE TITLE
error at install

### ISSUE THREAD

**Issue by FrancisVarga** [NiklasMerz/cordova-plugin-fingerprint-aio#42]
> cordova plugin add cordova-plugin-fingerprint-aio --save

```
Failed to install 'cordova-plugin-fingerprint-aio': Error
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:205:33
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Error: Failed to fetch plugin cordova-plugin-add-swift-support via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cordova-plugin-add-swift-support" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/francisvarga/.npm/_logs/2017-08-08T09_41_14_166Z-debug.log
```

**Comment by NiklasMerz** [comment]
Duplicate #41
