### ISSUE TITLE
Android NullPointerException Google Nexus 5x

### ISSUE THREAD

**Issue by ebo-zig** [NiklasMerz/cordova-plugin-fingerprint-aio#478]
## Description

After upgrading to the newest version (5.0.1), we are facing issues on the Google Nexus 5X regarding biometric authentication.

* What did you do?
Use biometric authentication on a Google Nexus 5X
* What did happen?
An error occurred
* What did you expect to happen?
No error

## Environment

* Plugin version: 5.0.1

### Logs

<details>
  <pre>Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int de.niklasmerz.cordova.biometric.BiometricActivityType.getValue()' on a null object reference
       at de.niklasmerz.cordova.biometric.PromptInfo$Builder.build(PromptInfo.java:112)
       at de.niklasmerz.cordova.biometric.BiometricActivity.onCreate(BiometricActivity.java:41)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)</pre>
</details>

**Comment by NiklasMerz** [comment]
See #475. Might be solved with release 5.0.2
