### ISSUE TITLE
Cancel on too many Invalid fingerprints screen. App Crash

### ISSUE THREAD

**Issue by nikhiltyagi1991** [NiklasMerz/cordova-plugin-fingerprint-aio#68]
## Description

Steps to Reproduce:
1. Call show function with below mentioned options.
2. Enter multiple incorrect fingerprints.
3. Close pattern lock using back button.
4. Recall show function with same options.
5. Click cancel on screen showing "Too many attempts.".
6. **APP CRASH**

Options:
```
{
clientId: 'Fingerprint-Demo',
clientSecret: 'password', //Only necessary for Android
disableBackup:false,  //Only for Android(optional)
localizedFallbackTitle: 'Use Pin', //Only for iOS
localizedReason: 'Please authenticate' //Only for iOS
}
```

## Environment

* Plugin version: cordova-plugin-fingerprint-aio 1.3.2
* android 6.1.2

### Logs

> FATAL EXCEPTION: main
                                                                    Process: -------, PID: 8036
                                                                    java.lang.IllegalStateException: Fragment FingerprintAuthenticationDialogFragment{5beb327} not attached to Activity
                                                                        at android.app.Fragment.getResources(Fragment.java:814)
                                                                        at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.updateStage(FingerprintAuthenticationDialogFragment.java:185)
                                                                        at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.goToBackup(FingerprintAuthenticationDialogFragment.java:180)
                                                                        at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onError(FingerprintAuthenticationDialogFragment.java:250)
                                                                        at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$1.run(FingerprintUiHelper.java:112)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6321)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-25 17:38:09.781 8036-8036/------- D/AppTracker: App Event: crash
10-25 17:38:09.806 8036-8036/------- I/Process: Sending signal. PID: 8036 SIG: 9

### Fixing this bug.
Simple check if the fragment activity is open in onError will prevent apps from crashing.

**Comment by nikhiltyagi1991** [comment]
Opened #69 Pull Request for this.

**Comment by NiklasMerz** [comment]
Thank you for this great bug report and pull request.
