### ISSUE TITLE
IllegalStateException error thrown on 'onAuthenticated'

### ISSUE THREAD

**Issue by NBAMj** [NiklasMerz/cordova-plugin-fingerprint-aio#77]
## Description

* What did you do?
Nothing
* What did happen?
One of my users is getting an error when prompted to authenticate with a fingerprint.
**Device info:** OnePlus5 (OnePlus5), Android 7.1

* What did you expect to happen?
The expected behavior is to be able to authenticate using fingerprint without issue.
* Type of issue (bug, feature request)
- [x] bug
- [ ] feature
- [ ] request

## Environment

* Plugin version: `1.2.1`
* Build environment (```cordova info```)
```
Node version: v6.10.0
Cordova version: 7.1.0
Available Android targets:
----------
id: 1 or "android-25"
     Name: Android API 25
     Type: Platform
     API level: 25
     Revision: 3
```
* cordova platform ls
```
Installed platforms:
  android 6.2.3
  ios 4.4.0
```

### Logs

```
java.lang.IllegalStateException: 
  at android.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1434)
  at android.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1452)
  at android.app.BackStackRecord.commitInternal (BackStackRecord.java:708)
  at android.app.BackStackRecord.commit (BackStackRecord.java:672)
  at android.app.DialogFragment.dismissInternal (DialogFragment.java:301)
  at android.app.DialogFragment.dismiss (DialogFragment.java:267)
  at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated (FingerprintAuthenticationDialogFragment.java:245)
  at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run (FingerprintUiHelper.java:148)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6334)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
```

**Comment by NiklasMerz** [comment]
Looks like some strange UI behaviour.

**Comment by akshaytaywade** [comment]
Still i am facing issue when the home button and finger print are pressed together the app went into back ground and app crashes 



   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1438)
        at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1456)
        at android.app.BackStackRecord.commitInternal(BackStackRecord.java:707)
        at android.app.BackStackRecord.commit(BackStackRecord.java:671)
        at android.app.DialogFragment.dismissInternal(DialogFragment.java:304)
        at android.app.DialogFragment.dismiss(DialogFragment.java:270)
        at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated(FingerprintAuthenticationDialogFragment.java:245)
        at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run(FingerprintUiHelper.java:148)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by NiklasMerz** [comment]
@akshaytaywade Could you pleas create a new issue to track this better.
