### ISSUE TITLE
Crash happens on Samsung S8+

### ISSUE THREAD

**Issue by yazantahhan** [NiklasMerz/cordova-plugin-fingerprint-aio#96]
Hi,

There is a crash that happens on Samsung S8+ and LG G6 after the Fingerprint is validated. 
I have tested in Samsung S8 with no issues.

Here is the crash stack trace:

`java.lang.IllegalStateException: IV has already been used. Reusing IV in encryption mode violates security best practices.
	at android.security.keystore.AndroidKeyStoreUnauthenticatedAESCipherSpi.addAlgorithmSpecificParametersToBegin(AndroidKeyStoreUnauthenticatedAESCipherSpi.java:244)
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:237)
	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:495)
	at javax.crypto.Cipher.doFinal(Cipher.java:1736)
	at de.niklasmerz.cordova.fingerprint.Fingerprint.tryEncrypt(Fingerprint.java:419)
	at de.niklasmerz.cordova.fingerprint.Fingerprint.onAuthenticated(Fingerprint.java:375)
	at de.niklasmerz.cordova.fingerprint.FingerprintAuthenticationDialogFragment.onAuthenticated(FingerprintAuthenticationDialogFragment.java:235)
	at de.niklasmerz.cordova.fingerprint.FingerprintUiHelper$2.run(FingerprintUiHelper.java:148)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

## Environment

Device: Samsung S8+
Android version: 8
Plugin version: 1.0.2
Installed Cordova platforms: Android 6.2.3

**Comment by NiklasMerz** [comment]
Ok that is strange. Do you know any other differences about those devices?

**Comment by EM15** [comment]
It's crashing in Motorola G5 Plus too. Sometimes works and sometimes don't. Like it were random.

**Comment by NiklasMerz** [comment]
Can you prive errors from logcat?

**Comment by lonwi** [comment]
I had few crashes on OnePlus OnePlus5T (OnePlus5T), 6144MB RAM, Android 8.0
java.lang.IllegalStateException: 
  at android.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1864)
  at android.app.FragmentManagerImpl.enqueueAction (FragmentManager.java:1887)
  at android.app.BackStackRecord.commitInternal (BackStackRecord.java:688)
  at android.app.BackStackRecord.commit (BackStackRecord.java:646)
  at android.app.DialogFragment.show (DialogFragment.java:230)
  at de.niklasmerz.cordova.fingerprint.Fingerprint$1.run (Fingerprint.java:215)
  at android.os.Handler.handleCallback (Handler.java:789)
  at android.os.Handler.dispatchMessage (Handler.java:98)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6809)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

**Comment by NiklasMerz** [comment]
Please have a look at #103. Looks like @devjocks fixed the issue and I was not aware of that.

**Comment by lonwi** [comment]
I had no crashes on my Samsung S8 + Duos G955FD. Unfortunately I do not have access to OnePlus5T directly, I will add it into the latest beta and check for crashes.

**Comment by lonwi** [comment]
I have few reports of this issue with v1.3.8 on ...
Motorola Moto G(4) Plus (athene_f), Android 7.0
Motorola Moto G (5S) Plus (sanders_n), Android 7.1
OnePlus OnePlus5 (OnePlus5), Android 8.1

**Comment by NiklasMerz** [comment]
@lonwi Did you try version 1.4.0. The mentioned fix is now released.

**Comment by NiklasMerz** [comment]
Please go to gitter for discussion or open another issue.
